version: "3.3"
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - ./src/DataBase:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  node:
    container_name: node_container
    image: node
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - .:/app/
      - /app/node_modules
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
